# Generated by Django 5.2 on 2025-04-17 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_customuser_options_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='contact must be 10 numbers', regex='^\\d{10}$')]),
        ),
    ]
